### ISSUE TITLE
Add options to customize symbols like `•`

### ISSUE THREAD

**Issue by satorunooshie** [Eliot00/git-lens.vim#10]
What do you think to add options to customize symbols like `•` as `termdebug_signs` does?

```
Change default signs 
							termdebug_signs
Termdebug uses the hex number of the breakpoint ID in the signcolumn to
represent breakpoints. if [it](https://vimhelp.org/motion.txt.html#it) [is](https://vimhelp.org/motion.txt.html#is) greater than "0xFF"[,](https://vimhelp.org/motion.txt.html#%2C) then [it](https://vimhelp.org/motion.txt.html#it) will be displayed
[as](https://vimhelp.org/motion.txt.html#as) "F+"[,](https://vimhelp.org/motion.txt.html#%2C) due to we really only have two screen cells for the sign.

If you want to customize the breakpoint signs: 
	let g:termdebug_config['sign'] = '>>'
If there [is](https://vimhelp.org/motion.txt.html#is) no g:terminal_config yet you can use: 
	let g:termdebug_config = {'sign': '>>'}

After this, breakpoints will be displayed [as](https://vimhelp.org/motion.txt.html#as) >> in the signcolumn.
```

**Comment by Eliot00** [comment]
If I understand correctly, this option already exists

```vim
g:GIT_LENS_CONFIG = {
    blame_prefix: '••••',
}
```

**Comment by satorunooshie** [comment]
Thanks for reply.
```
g:GIT_LENS_CONFIG = {
  blame_prefix: '    ---- ',
}
```
I'm pointing symbols at https://github.com/Eliot00/git-lens.vim/blob/508e85748e4fa2028a5eaf144adbe3659002b592/autoload/git_lens/blame.vim#L226 not prefix.

<img width="471" alt="image" src="https://github.com/Eliot00/git-lens.vim/assets/64164948/413abb1d-69f9-470f-86f1-0160248eaf5b">

**Comment by Eliot00** [comment]
I see, but adding a separate configuration for the separator seems not flexible enough...

I quickly did a minimal verification and added a 'blame_template' configuration item. The effect is as shown below

![image](https://github.com/Eliot00/git-lens.vim/assets/18375468/62175def-733c-4abe-a055-deaedff2abd7)
