### ISSUE TITLE
`ShowBlameWithVirtualText` is not called

### ISSUE THREAD

**Issue by Dabulv** [Eliot00/git-lens.vim#11]
The git-lens.vim not run very well on one of my linux system, while ok on my macOS. And finally locates to `ShowBlameWithVirtualText` is not called. I debug by add codes `echoerr` before, after and within `ShowBlameWithVirtualText`, only `echoerr` in `ShowBlameWithVirtualText` is not executed.

170     blame_job = job_start(blame_command, {
171         "out_cb": (channel, message) => ShowBlameWithVirtualText(message),
172         "mode": "raw"
173     })

**Comment by Eliot00** [comment]
Can you `echo blame_command` and try it in shell?

**Comment by Dabulv** [comment]
Thanks a lot.

Trying blame_command in shell: 
Unknown option: -C
`usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]`

And I fix this problem by change code from
`154     const blame_command = [`
`155         'git',`
`156         '-C',`
to 
`154     const blame_command = [`
`155         'git',`
`156         '-c',`
