### ISSUE TITLE
Does it still support delay?

### ISSUE THREAD

**Issue by wanaiqing** [Eliot00/git-lens.vim#6]
blame_delay is not working...

**Comment by Eliot00** [comment]
I removed delay option, because this plugin now calls git commands asynchronously

**Comment by wanaiqing** [comment]
@Eliot00 how can I enable delay currently?

**Comment by Eliot00** [comment]
This feature has been removed, I wonder why you need a delay?

wanaiqing ***@***.***> 于2023年6月26日周一 17:18写道：

**Comment by wanaiqing** [comment]
@Eliot00 I think blame with a delay should be a natural feature, otherwise it makes blame info looks like a part of source code.

**Comment by Eliot00** [comment]
Ok, I will find time to add this feature back, or you can create a PR :)

wanaiqing ***@***.***> 于2023年6月26日周一 22:02写道：

**Comment by wanaiqing** [comment]
Waiting for its back

**Comment by Eliot00** [comment]
[This branch](https://github.com/Eliot00/git-lens.vim/tree/delay) support delay config again, not sure if everyone likes this feature, so don't merge it into the main branch for now.

**Comment by wanaiqing** [comment]
> [This branch](https://github.com/Eliot00/git-lens.vim/tree/delay) support delay config again, not sure if everyone likes this feature, so don't merge it into the main branch for now.

Does it has an impact on other features?

**Comment by Eliot00** [comment]
> Does it has an impact on other features?

Not sure for yet.

> And btw how to switch to this branch in vim by plugin like Vim-plug?

According to https://github.com/junegunn/vim-plug#example

```vim
Plug 'Eliot00/git-lens.vim', { 'branch': 'delay' }
```

**Comment by wanaiqing** [comment]
It seems buggy once a buffer loaded...
For examples:
1.for a short first line (blame info rendered twice)
`[some text        Author · Date · Log     Author · Date · Log]`
2.for a long first line (blame wrapped)
`[this is a line that is long enough to touch the right.      ]`
`[  Author · Date · Log                                       ]`

**Comment by wanaiqing** [comment]
> It seems buggy once a buffer loaded... For examples: 1.for a short first line (blame info rendered twice) `[some text Author · Date · Log Author · Date · Log]` 2.for a long first line (blame wrapped) `[this is a line that is long enough to touch the right. ]` `[ Author · Date · Log ]`

I think it's a combination....
And repeat may be more than twice...

**Comment by Eliot00** [comment]
Thanks for your feedback, already fixed. @wanaiqing

**Comment by wanaiqing** [comment]
@Eliot00 Great, thanks

**Comment by wanaiqing** [comment]
I think I have to reopen this...
The repetition problem comes again, it may be not just an issue for initializing a buffer, I accidentally triggered it after the buffer loading but not sure what's the cause.

**Comment by Eliot00** [comment]
~Moving the cursor when the previous timer is about to execute will cause `timer_stop` to be too late to clean up~

The cursor moves too fast and asynchronously displays the old blame on a new line. @wanaiqing 

```
line changed ->
timer stop ->
clear virtual text ->
set time out show -> after 500ms
                               -> async job started
line changed ->
timer stop ->
clear virtual text ->
                            -> async job finished, render old blame info in new line
time out new blame info
```

**Comment by Eliot00** [comment]
This problem is only caused by moving the cursor just when the asynchronous task is not completed

**Comment by wanaiqing** [comment]
> This problem is only caused by moving the cursor just when the asynchronous task is not completed

Seems right.

**Comment by Eliot00** [comment]
Temporary solution: clean up virtual text again before asynchronous task rendering

**Comment by wanaiqing** [comment]
Take your time, I'll wait for it to be a sophisticated feature on main branch
