### ISSUE TITLE
Why is the virtual text taking so long to pop up?

### ISSUE THREAD

**Issue by jclsn** [Eliot00/git-lens.vim#8]
For me it takes ~1 second until the blame pops up. Can this be improved somehow?

**Comment by jclsn** [comment]
Seems like the blame delay is responsible for this. Why is it set to 500ms? That is too long imo

**Comment by jclsn** [comment]
Ah can be adjusted in the config. Closing...

**Comment by Eliot00** [comment]
Thanks for your reminder, I have updated the README.md.
